### ISSUE TITLE
Docco-plus is not running properly

### ISSUE THREAD

**Issue by eltonjr** [smravi/docco-plus#16]
Hey guys, Docco is not running properly on my project anymore

Example:  
```
$ node node_modules/docco-plus/bin/docco-plus env.js 
docco: no stylesheet file specified
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at write (/home/elton/workspace/src/gitlab.neoway.com.br/path/to/project/node_modules/docco/docco.js:149:17)
    at /home/elton/workspace/src/gitlab.neoway.com.br/path/to/project/node_modules/docco/docco.js:48:11
    at /home/elton/workspace/src/gitlab.neoway.com.br/path/to/project/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
```

My package.json contains
```
...
"dependencies": {
    "amqp": "^0.2.4",
    "docco-plus": "~1.0.3",
    "jshint": "^2.8.0",
    "mocha": "^2.3.3",
    "request": "^2.65.0",
    "should": "^7.1.0"
  }
```

Thanks!

**Comment by pranavjha** [comment]
works for me..
Can you give more details (node version / github repo where you are trying it) so that I can debug?

**Comment by eltonjr** [comment]
I figured out I was using an updated version of NPM and Node with older versions of docco-plus

Node 7.5.0  
NPM  4.3.0  
Docco-plus 1.0.3  

Simply updating to docco-plus 2.0.0 solved the issue

Thanks for your time!
